### ISSUE TITLE
Null for temperature

### ISSUE THREAD

**Issue by lmc4me** [jhschuster/homebridge-intesisweb#1]
Connects to device, shows in homekit, though unable to turn air conditioner on / off, no temperature dial. Seems to login fine, then unable to grab all the services.
Would appreciate if you can have a look through to see where the error is.

<img width="1185" alt="Screen Shot 2020-02-08 at 6 09 07 pm" src="https://user-images.githubusercontent.com/32088081/74081038-854e2280-4a9e-11ea-9257-1226a4ab3a32.png">

**Comment by jhschuster** [comment]
I've fixed this. The temperature and mode setting was completely broken.

**Comment by jhschuster** [comment]
I had been using this plugin only to turn the units on and off, as well as monitoring their settings. Until today I'd never tried to get changing things to work.
